# Generated by Django 5.0.4 on 2025-05-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operatorler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_adi', models.CharField(max_length=255)),
                ('op_sembol', models.CharField(max_length=255)),
                ('sembol', models.CharField(blank=True, max_length=255, null=True)),
                ('op_grubu', models.CharField(choices=[('aritmatik', 'Aritmetik Operatörler'), ('karar', 'KARAR Operatörler'), ('karsilastirma', 'Karşılaştırma Operatörleri'), ('diger', 'Diğer Operatörler')], default='ARITMETIK', max_length=50)),
            ],
        ),
    ]
