# Generated by Django 5.0.4 on 2025-05-04 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sozluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terim', models.CharField(max_length=50, unique=True)),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('onayli', models.BooleanField(default=False)),
                ('ekleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SozlukDil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dil', models.CharField(max_length=10)),
                ('baslik', models.CharField(max_length=200)),
                ('tanim', models.TextField()),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('ornek', models.TextField(blank=True, null=True)),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('onayli', models.BooleanField(default=False)),
                ('ekleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sozluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceviriler', to='akademi.sozluk')),
            ],
            options={
                'unique_together': {('sozluk', 'dil')},
            },
        ),
    ]
