# Generated by Django 5.0.4 on 2025-05-04 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('1m', '1 Dakikalık'), ('5m', '5 Dakikalık'), ('15m', '15 Dakikalık'), ('30m', '30 Dakikalık'), ('1h', '1 Saatlik'), ('2h', '2 Saatlik'), ('4h', '4 Saatlik'), ('1d', '1 Günlük'), ('1w', '1 Haftalık')], max_length=3)),
                ('onay', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MarketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(choices=[('spot', 'Spot'), ('futures', 'Futures')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pariteler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pariteler', models.CharField(max_length=50, unique=True)),
                ('base', models.CharField(blank=True, max_length=20, null=True)),
                ('quote', models.CharField(blank=True, max_length=20, null=True)),
                ('tip', models.CharField(choices=[('parite', 'Normal Parite'), ('endeks', 'Endeks / Gösterge')], default='parite', max_length=10)),
                ('onay', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PariteIntervalMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onay', models.BooleanField(default=True)),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mumlar.interval')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mumlar.markettype')),
                ('parite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mumlar.pariteler')),
            ],
            options={
                'unique_together': {('parite', 'interval', 'market')},
            },
        ),
    ]
