# Generated by Django 5.0.4 on 2025-05-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiyasaOzeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now_add=True)),
                ('artan_coin_sayisi', models.IntegerField()),
                ('dusen_coin_sayisi', models.IntegerField()),
                ('ortalama_volatilite', models.FloatField()),
                ('toplam_hacim', models.FloatField()),
                ('btc_dominans', models.FloatField()),
                ('yorum', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
