# Generated by Django 5.0.4 on 2025-05-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coinler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sembol', models.CharField(max_length=10)),
                ('fiyat', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('toplam_piyasa_degeri', models.BigIntegerField(blank=True, null=True)),
                ('volume_1h', models.BigIntegerField(blank=True, null=True)),
                ('volume_24h', models.BigIntegerField(blank=True, null=True)),
                ('dolasimdaki_arz', models.BigIntegerField(blank=True, null=True)),
                ('toplam_arz', models.BigIntegerField(blank=True, null=True)),
                ('max_arz', models.BigIntegerField(blank=True, null=True)),
                ('yuzde_deg_son_1h', models.FloatField(blank=True, null=True)),
                ('yuzde_deg_son_24h', models.FloatField(blank=True, null=True)),
                ('yuzde_deg_son_7d', models.FloatField(blank=True, null=True)),
                ('son_guncelleme', models.DateTimeField(auto_now=True)),
                ('coin_gif', models.CharField(blank=True, max_length=50, null=True)),
                ('teknolojisi', models.TextField(blank=True, null=True)),
                ('ureten_firma', models.CharField(blank=True, max_length=100, null=True)),
                ('merkeziyetsiz_mi', models.BooleanField(default=True)),
                ('hakkinda', models.TextField(blank=True, null=True)),
                ('enflasyonist_mi', models.BooleanField(default=False)),
                ('resmi_web_sitesi', models.URLField(blank=True, null=True)),
                ('whitepaper_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coinler',
            },
        ),
    ]
