# Generated by Django 5.0.4 on 2025-05-04 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indikatorler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=255, unique=True)),
                ('kutuphane', models.CharField(choices=[('ta', 'TA'), ('ta-lib', 'TA-Lib'), ('custom', 'Custom')], default='custom', max_length=10)),
                ('indikator_grubu', models.CharField(choices=[('trend', 'Trend'), ('momentum', 'Momentum'), ('oynaklik', 'Oynaklık'), ('hacim', 'Hacim'), ('custom', 'Custom')], default='custom', max_length=255)),
                ('aktif_mi', models.BooleanField(default=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('kullanim_aciklamasi', models.TextField(blank=True, null=True)),
                ('indikator_ciftleri', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndikatorCiktilari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indikator_adi', models.CharField(blank=True, max_length=255, null=True)),
                ('cikti_adi', models.CharField(max_length=255)),
                ('cikti_kodu', models.CharField(max_length=255)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciktilar', to='indikatorler.indikatorler')),
            ],
        ),
        migrations.CreateModel(
            name='IndikatorParametreleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indikator_adi', models.CharField(blank=True, max_length=255, null=True)),
                ('parametre_adi', models.CharField(max_length=255)),
                ('varsayilan_deger', models.CharField(blank=True, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('paramatre_tipi', models.CharField(blank=True, max_length=255, null=True)),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametreler', to='indikatorler.indikatorler')),
            ],
        ),
    ]
